<a href="https://colab.research.google.com/github/harshavanga/Data690-StatsANDVisualization/blob/main/Assignment%206/assignment_06_HarshaVanga.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment 06
### Note:
- For visualization, you should use Matplotlib, seaborn, or Plotly Express 
- Use this notebook as your template and follow the instructions

The first half of this assignment is similar to assignment 04.

This gives you a chance to refresh.

The second half is new and gives you a chance to perform additional practices.

You also get a chance to use some of the Python libraries and techniques.

The links to the zip file is:

- https://collegescorecard.ed.gov/data (This web page contains the link to the zip file)

- https://ed-public-download.app.cloud.gov/downloads/CollegeScorecard_Raw_Data_09012022.zip (The link to the zip file)

You can run `!wget` command in Colab notebook to retrieve it directly, then run `!unzip` command to extract files (I have provided the cells to do so next for your convenience)

Your folder structure should look like this in your Colab enviroment:

- ...
- 'MERGED1996_97_PP.csv',
- 'MERGED2015_16_PP.csv',
- ...
- 'MERGED2017_18_PP.csv'
- ...

**Note: you should refresh the folder to see all files.**

## Step 1 - Retrieve the zip file

In [2]:
!wget https://ed-public-download.app.cloud.gov/downloads/CollegeScorecard_Raw_Data_09012022.zip

--2022-10-10 02:39:46--  https://ed-public-download.app.cloud.gov/downloads/CollegeScorecard_Raw_Data_09012022.zip
Resolving ed-public-download.app.cloud.gov (ed-public-download.app.cloud.gov)... 3.30.49.38, 3.30.138.208, 2600:1f12:18a:7d01:ad67:f64c:95d6:78ed, ...
Connecting to ed-public-download.app.cloud.gov (ed-public-download.app.cloud.gov)|3.30.49.38|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 410294884 (391M) [application/zip]
Saving to: ‘CollegeScorecard_Raw_Data_09012022.zip’

CollegeScorecard_Ra 100%[===================>] 391.29M  18.8MB/s    in 22s

2022-10-10 02:40:09 (17.6 MB/s) - ‘CollegeScorecard_Raw_Data_09012022.zip’ saved [410294884/410294884]

## Step 2 - Unzip the zip file

In [3]:
!unzip CollegeScorecard_Raw_Data_09012022.zip

Archive:  CollegeScorecard_Raw_Data_09012022.zip
 extracting: Crosswalks.zip
  inflating: data.yaml
  inflating: FieldOfStudyData1415_1516_PP.csv
  inflating: FieldOfStudyData1516_1617_PP.csv
  inflating: FieldOfStudyData1617_1718_PP.csv
  inflating: FieldOfStudyData1718_1819_PP.csv
  inflating: MERGED1996_97_PP.csv
  inflating: MERGED1997_98_PP.csv
  inflating: MERGED1998_99_PP.csv
  inflating: MERGED1999_00_PP.csv
  inflating: MERGED2000_01_PP.csv
  inflating: MERGED2001_02_PP.csv
  inflating: MERGED2002_03_PP.csv
  inflating: MERGED2003_04_PP.csv
  inflating: MERGED2004_05_PP.csv
  inflating: MERGED2005_06_PP.csv
  inflating: MERGED2006_07_PP.csv
  inflating: MERGED2007_08_PP.csv
  inflating: MERGED2008_09_PP.csv
  inflating: MERGED2009_10_PP.csv
  inflating: MERGED2010_11_PP.csv
  inflating: MERGED2011_12_PP.csv
  inflating: MERGED2012_13_PP.csv
  inflating: MERGED2013_14_PP.csv
  inflating: MERGED2014_15_PP.csv
  inflating: MERGED2015_16_PP.csv
  inflating: MERGED2016_17_PP.csv
  inflating: MERGED2017_18_PP.csv
  inflating: MERGED2018_19_PP.csv
  inflating: MERGED2019_20_PP.csv
  inflating: MERGED2020_21_PP.csv
  inflating: Most-Recent-Cohorts-Field-of-Study.csv
  inflating: Most-Recent-Cohorts-Institution.csv

## Step 3 - Import Libraries

In [4]:
#(Write code below)
import pandas as pd
import plotly.express as px
import matplotlib as mlt
import numpy
import os

## Step 4 - Display the current working directory using os.getcwd()

You would need to import a standard Python library called os which stands for operating system. so place that import statement in the previous cell. Since your notebook and your data files may or may not in the same folder, you want to make sure what the current working folder is and how to access a data file in a different folder.

In [5]:
#(Write code below)
os.getcwd()

'/content'

## Step 5 - Get the list of file names

os library has a method call listdir which generates a list of files in a directory/folder. Use this method to assign the contents (list of file names) of the data folder to a variable and display it. If necessary, you can use ../ construct to traverse to the parent folder and then to another foloder parallel to the current folder

In [6]:
#(Write code below)
name_list = os.listdir()
name_list

['.config',
 'MERGED2006_07_PP.csv',
 'MERGED2009_10_PP.csv',
 'MERGED2003_04_PP.csv',
 'MERGED1998_99_PP.csv',
 'Crosswalks.zip',
 'MERGED2012_13_PP.csv',
 'MERGED2019_20_PP.csv',
 'MERGED2011_12_PP.csv',
 'MERGED2014_15_PP.csv',
 'Most-Recent-Cohorts-Field-of-Study.csv',
 'MERGED2000_01_PP.csv',
 'MERGED2007_08_PP.csv',
 'MERGED2016_17_PP.csv',
 'FieldOfStudyData1718_1819_PP.csv',
 'MERGED2018_19_PP.csv',
 'MERGED2008_09_PP.csv',
 'MERGED2002_03_PP.csv',
 'MERGED2004_05_PP.csv',
 'MERGED2010_11_PP.csv',
 'MERGED2013_14_PP.csv',
 'MERGED2005_06_PP.csv',
 'FieldOfStudyData1516_1617_PP.csv',
 'MERGED1999_00_PP.csv',
 'MERGED2015_16_PP.csv',
 'MERGED1996_97_PP.csv',
 'FieldOfStudyData1415_1516_PP.csv',
 'FieldOfStudyData1617_1718_PP.csv',
 'MERGED2017_18_PP.csv',
 'data.yaml',
 'Most-Recent-Cohorts-Institution.csv',
 'MERGED1997_98_PP.csv',
 'MERGED2020_21_PP.csv',
 'CollegeScorecard_Raw_Data_09012022.zip',
 'MERGED2001_02_PP.csv',
 'sample_data']

## Step 6 - Process only the yearly data files

The folder contains files that are not the yearly data files. Write code to remove the unwanted files from the list variable.

Note: don't remove/delete these files from the folder in the folder.
For example, use the file extension to only use the csv files or use the name patter - data file name begins with "MERGED". You can use the concept of list comprehension to write just *one* line of code as well as using a for loop, your choice.

In [7]:
year_list = [file_name for file_name in name_list if file_name.startswith("MERGED")]

year_list

['MERGED2006_07_PP.csv',
 'MERGED2009_10_PP.csv',
 'MERGED2003_04_PP.csv',
 'MERGED1998_99_PP.csv',
 'MERGED2012_13_PP.csv',
 'MERGED2019_20_PP.csv',
 'MERGED2011_12_PP.csv',
 'MERGED2014_15_PP.csv',
 'MERGED2000_01_PP.csv',
 'MERGED2007_08_PP.csv',
 'MERGED2016_17_PP.csv',
 'MERGED2018_19_PP.csv',
 'MERGED2008_09_PP.csv',
 'MERGED2002_03_PP.csv',
 'MERGED2004_05_PP.csv',
 'MERGED2010_11_PP.csv',
 'MERGED2013_14_PP.csv',
 'MERGED2005_06_PP.csv',
 'MERGED1999_00_PP.csv',
 'MERGED2015_16_PP.csv',
 'MERGED1996_97_PP.csv',
 'MERGED2017_18_PP.csv',
 'MERGED1997_98_PP.csv',
 'MERGED2020_21_PP.csv',
 'MERGED2001_02_PP.csv']

## Step 7 - Load data files
 
Now that you have a clean list of the yearly files, you want to loop through them and read them into a dataframe one at a time. You only load six columns: ["UNITID", "INSTNM", "STABBR", "REGION", "ADM_RATE", "TUITIONFEE_IN"].

You should use "usecols" option of Pandas to avoid reading unwanted columns. You also want to add a new column call "YEAR" to differentiate the data frames from each other. The YEAR variable should be yyyy format so tht you can convert them into integer. If you use the format yyyy-yy (such as 1997-98 school year), you will not be able to convert them directly to integer. If you use scatter plot, the YEAR needs to be converted to integer or float. 

You would use an empty list and append the yearly dataframes to the list. After all data files are loaded and appended to the list, you would use Pandas to concatenate them into a new single data frame.

Note: this exercise incorporates many techques we learned before:

- list (creating an empty, append an item to the list)
- for loop 
- read only the needed columns from a file (using usecols option)
- add a new column to a data frame
- concatenate multiple dataframes into a single one

This exercise may appear challenging but it worths the effort. You will learn a lot and love it. I promise.

In [8]:
#(Write code here)

year_list.sort()

print("processing file", year_list[0])
df_all = pd.read_csv("/content/" + year_list[0], usecols=["UNITID", "INSTNM", "STABBR", "REGION", "ADM_RATE", "TUITIONFEE_IN"])
df_all["year"] = year_list[0][6:10]
print(df_all.shape)

for yearly_file in year_list[1:]:
    print("processing file", yearly_file)
    df = pd.read_csv("/content/" + yearly_file, usecols=["UNITID", "INSTNM", "STABBR", "REGION", "ADM_RATE", "TUITIONFEE_IN"])
    df["year"] = yearly_file[6:10]
    df_all = df_all.append(df, ignore_index = True)
    print(df_all.shape)

processing file MERGED1996_97_PP.csv
(7007, 7)
processing file MERGED1997_98_PP.csv
(13941, 7)
processing file MERGED1998_99_PP.csv
(20643, 7)
processing file MERGED1999_00_PP.csv
(27252, 7)
processing file MERGED2000_01_PP.csv
(33906, 7)
processing file MERGED2001_02_PP.csv
(40631, 7)
processing file MERGED2002_03_PP.csv
(47283, 7)
processing file MERGED2003_04_PP.csv
(53956, 7)
processing file MERGED2004_05_PP.csv
(60703, 7)
processing file MERGED2005_06_PP.csv
(67602, 7)
processing file MERGED2006_07_PP.csv
(74553, 7)
processing file MERGED2007_08_PP.csv
(81524, 7)
processing file MERGED2008_09_PP.csv
(88579, 7)
processing file MERGED2009_10_PP.csv
(95796, 7)
processing file MERGED2010_11_PP.csv
(103266, 7)
processing file MERGED2011_12_PP.csv
(111012, 7)
processing file MERGED2012_13_PP.csv
(118874, 7)
processing file MERGED2013_14_PP.csv
(126743, 7)
processing file MERGED2014_15_PP.csv
(134509, 7)
processing file MERGED2015_16_PP.csv
(142175, 7)
processing file MERGED2016_17_PP.csv
(149413, 7)
processing file MERGED2017_18_PP.csv
(156525, 7)
processing file MERGED2018_19_PP.csv
(163332, 7)
processing file MERGED2019_20_PP.csv
(170026, 7)
processing file MERGED2020_21_PP.csv
(176707, 7)

In [9]:
df_all.sample(10)

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,year
38025,219596,Tennessee College of Applied Technology-Athens,TN,5.0,NaN,NaN,2001
51974,240338,Wisconsin Lutheran College,WI,3.0,0.8362,15850.0,2003
143839,168430,Worcester State University,MA,1.0,0.7056,9202.0,2016
166162,212452,Faith Theological Seminary,MD,2.0,1.0000,8392.0,2019
100519,366678,ITT Technical Institute-Austin,TX,6.0,0.3988,18048.0,2010
168530,459213,Gurnick Academy of Medical Arts,CA,8.0,NaN,NaN,2019
145949,233842,Union Presbyterian Seminary,VA,5.0,NaN,NaN,2016
131672,414124,Motoring Technical Training Institute,MA,1.0,0.7756,NaN,2014
114440,214315,Newport Business Institute-Lower Burrell,PA,2.0,NaN,12515.0,2012
35532,155830,Salina Area Technical College,KS,4.0,NaN,NaN,2001

## Step 8 - Explore the new dataframe 

For example, # of observations, varibles, head, tail, sample, missing values, statistics, etc.

In [10]:
df_all.shape

(176707, 7)

In [11]:
df_all.columns

Index(['UNITID', 'INSTNM', 'STABBR', 'REGION', 'ADM_RATE', 'TUITIONFEE_IN',
       'year'],
      dtype='object')

In [12]:
df_all.head()

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,year
0,100636,Community College of the Air Force,AL,0.0,NaN,NaN,1996
1,100654,Alabama A & M University,AL,5.0,NaN,NaN,1996
2,100663,University of Alabama at Birmingham,AL,5.0,NaN,NaN,1996
3,100672,ALABAMA AVIATION AND TECHNICAL COLLEGE,AL,5.0,NaN,NaN,1996
4,100690,Amridge University,AL,5.0,NaN,NaN,1996

In [13]:
df_all.tail()

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,year
176702,49576719,Pennsylvania State University-Penn State Wilke...,PA,2.0,NaN,13604.0,2020
176703,49576720,Pennsylvania State University-Penn State York,PA,2.0,NaN,14486.0,2020
176704,49576721,Pennsylvania State University-Penn State Great...,PA,2.0,NaN,NaN,2020
176705,49576722,Pennsylvania State University-Penn State Harri...,PA,2.0,NaN,15216.0,2020
176706,49576723,Pennsylvania State University-Penn State Brand...,PA,2.0,NaN,14486.0,2020

In [14]:
df_all.sample(5)

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,year
44338,212179,Harrisburg Institute of Trade and Technology,PA,2.0,NaN,8950.0,2002
142661,123493,Charles A Jones Career and Education Center,CA,8.0,NaN,NaN,2016
170046,101301,George C Wallace State Community College-Selma,AL,5.0,NaN,4560.0,2020
46158,397270,Bristol University,CA,8.0,NaN,NaN,2002
141897,16884701,Baker College of Owosso,MI,3.0,NaN,8640.0,2015

In [15]:
df_all.isnull().sum()

UNITID                0
INSTNM                0
STABBR                0
REGION                1
ADM_RATE         127844
TUITIONFEE_IN     89840
year                  0
dtype: int64

In [16]:
df_all.describe()

             UNITID         REGION      ADM_RATE  TUITIONFEE_IN
count  1.767070e+05  176706.000000  48863.000000   86867.000000
mean   1.054338e+06       4.559279      0.693785   12037.588290
std    4.959072e+06       2.188341      0.217019   10462.970227
min    1.006360e+05       0.000000      0.000000       0.000000
25%    1.641730e+05       3.000000      0.556700    3936.000000
50%    2.136310e+05       5.000000      0.719500    9422.000000
75%    4.137780e+05       6.000000      0.857100   16490.000000
max    4.957672e+07       9.000000      1.000000   74787.000000

## Step 9 - UMBC 

The dataframe contains many years of data of all U.S. colleges. let's just look at UMBC. Filter/query the dataframe to retrieve only rows that belong to UMBC (one row represent one year). Save the UMNC data to a new data frame. using a new variable for the UMBC data frame, so that the old big data frame is still available for later use.

In [17]:
#(Write code here)
umbc_df = df_all[df_all["INSTNM"].str.contains("University of Maryland-Baltimore County")]
umbc_df

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,year
2151,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1996
9056,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1997
15923,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1998
22598,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1999
29178,163268,University of Maryland-Baltimore County,MD,2.0,NaN,5490.0,2000
35821,163268,University of Maryland-Baltimore County,MD,2.0,0.6551,5910.0,2001
42524,163268,University of Maryland-Baltimore County,MD,2.0,0.6327,6362.0,2002
49156,163268,University of Maryland-Baltimore County,MD,2.0,0.5757,7388.0,2003
55786,163268,University of Maryland-Baltimore County,MD,2.0,0.7014,8020.0,2004
62522,163268,University of Maryland-Baltimore County,MD,2.0,0.7143,8520.0,2005
69401,163268,University of Maryland-Baltimore County,MD,2.0,0.7153,8622.0,2006
76332,163268,University of Maryland-Baltimore County,MD,2.0,0.6895,8708.0,2007
83291,163268,University of Maryland-Baltimore County,MD,2.0,0.7174,8780.0,2008
90324,163268,University of Maryland-Baltimore County,MD,2.0,0.6890,8872.0,2009
97506,163268,University of Maryland-Baltimore County,MD,2.0,0.6589,9171.0,2010
104960,163268,University of Maryland-Baltimore County,MD,2.0,0.6081,9467.0,2011
112672,163268,University of Maryland-Baltimore County,MD,2.0,0.6035,9764.0,2012
120503,163268,University of Maryland-Baltimore County,MD,2.0,0.6315,10068.0,2013
128353,163268,University of Maryland-Baltimore County,MD,2.0,0.5961,10384.0,2014
136064,163268,University of Maryland-Baltimore County,MD,2.0,0.5942,11006.0,2015
143685,163268,University of Maryland-Baltimore County,MD,2.0,0.5683,11264.0,2016
150891,163268,University of Maryland-Baltimore County,MD,2.0,0.6021,11518.0,2017
157940,163268,University of Maryland-Baltimore County,MD,2.0,0.5794,11778.0,2018
164723,163268,University of Maryland-Baltimore County,MD,2.0,0.6103,12028.0,2019
171401,163268,University of Maryland-Baltimore County,MD,2.0,0.6948,9420.0,2020

## Step 10 - Explore the new dataframe

For example, # of observations, varibles, head, tail, sample, missing values, statistics, etc

In [18]:
umbc_df.shape

(25, 7)

In [19]:
umbc_df.columns

Index(['UNITID', 'INSTNM', 'STABBR', 'REGION', 'ADM_RATE', 'TUITIONFEE_IN',
       'year'],
      dtype='object')

In [20]:
umbc_df.head()

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,year
2151,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1996
9056,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1997
15923,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1998
22598,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1999
29178,163268,University of Maryland-Baltimore County,MD,2.0,NaN,5490.0,2000

In [21]:
umbc_df.tail()

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,year
143685,163268,University of Maryland-Baltimore County,MD,2.0,0.5683,11264.0,2016
150891,163268,University of Maryland-Baltimore County,MD,2.0,0.6021,11518.0,2017
157940,163268,University of Maryland-Baltimore County,MD,2.0,0.5794,11778.0,2018
164723,163268,University of Maryland-Baltimore County,MD,2.0,0.6103,12028.0,2019
171401,163268,University of Maryland-Baltimore County,MD,2.0,0.6948,9420.0,2020

In [22]:
umbc_df.sample(5)

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,year
157940,163268,University of Maryland-Baltimore County,MD,2.0,0.5794,11778.0,2018
29178,163268,University of Maryland-Baltimore County,MD,2.0,NaN,5490.0,2000
90324,163268,University of Maryland-Baltimore County,MD,2.0,0.6890,8872.0,2009
62522,163268,University of Maryland-Baltimore County,MD,2.0,0.7143,8520.0,2005
112672,163268,University of Maryland-Baltimore County,MD,2.0,0.6035,9764.0,2012

In [23]:
umbc_df.isnull().sum()

UNITID           0
INSTNM           0
STABBR           0
REGION           0
ADM_RATE         5
TUITIONFEE_IN    4
year             0
dtype: int64

In [24]:
umbc_df.describe()

         UNITID  REGION   ADM_RATE  TUITIONFEE_IN
count      25.0    25.0  20.000000      21.000000
mean   163268.0     2.0   0.641880    9168.571429
std         0.0     0.0   0.051853    1854.082079
min    163268.0     2.0   0.568300    5490.000000
25%    163268.0     2.0   0.600600    8520.000000
50%    163268.0     2.0   0.632100    9171.000000
75%    163268.0     2.0   0.690825   10384.000000
max    163268.0     2.0   0.717400   12028.000000

## Step 11 - Plot UMBC's in-state tuition overtime Bar Chart

In [25]:
fig = px.bar(umbc_df, y = "TUITIONFEE_IN", x = "year")
fig.show()

## Step 12 - Plot UMBC's in-state tuition overtime using line Chart

In [26]:
#(Write code here)
fig = px.line(umbc_df, x="year", y="TUITIONFEE_IN")
fig.show()

## Step 13 - Tuition Growth Rate

Now let's look at the tuition growth rate year over year. We need to calculate UMBC tuition change percentage each year. First convert the TUITIONFEE_IN column to a Python List

In [27]:
#(Write code here)
inst_tuition = umbc_df['TUITIONFEE_IN'].to_list()
inst_tuition

[nan,
 nan,
 nan,
 nan,
 5490.0,
 5910.0,
 6362.0,
 7388.0,
 8020.0,
 8520.0,
 8622.0,
 8708.0,
 8780.0,
 8872.0,
 9171.0,
 9467.0,
 9764.0,
 10068.0,
 10384.0,
 11006.0,
 11264.0,
 11518.0,
 11778.0,
 12028.0,
 9420.0]

In [29]:
growth_rate = [(inst_tuition[k] - inst_tuition[k-1])/inst_tuition[k-1] for k in range(len(inst_tuition))]
growth_rate

[nan,
 nan,
 nan,
 nan,
 nan,
 0.07650273224043716,
 0.07648054145516074,
 0.16127004086765168,
 0.08554412560909583,
 0.06234413965087282,
 0.011971830985915493,
 0.009974483878450475,
 0.008268259072117593,
 0.010478359908883827,
 0.03370153291253381,
 0.03227565151019518,
 0.03137213478398648,
 0.031134780827529702,
 0.03138657131505761,
 0.05989984591679507,
 0.02344175904052335,
 0.022549715909090908,
 0.022573363431151242,
 0.021226014603498048,
 -0.2168274027269704]

## Step 14 - Loop through the list and calculate the % change each year over the prior year

This takes some effort. Not hard, just some abstract/logical thinking and some experiments. Have fun on this one.

In [30]:
 #(Write code here)
growth_rate = [growth_rate[k]/growth_rate[k-1] for k in range(len(growth_rate))]
growth_rate

[nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 0.9997099347353153,
 2.108641463557127,
 0.5304402798489939,
 0.7287951008554564,
 0.19202816901408448,
 0.8331627710235102,
 0.8289410432534638,
 1.2672994178688939,
 3.2162984670874657,
 0.9576909036737514,
 0.972006243594392,
 0.9924342427414938,
 1.0080871128954687,
 1.908454584462952,
 0.39134923774404257,
 0.9619464081219168,
 1.0010486838129433,
 0.9403124469349635,
 -10.21517259727303]

## Step 15 - Round up the percentage to two decimal points

The resulting number has many decimal points which are unnecessary and not visually appealing. You can use for loop. Or better, use list comprehension for simplicity/brevity.

In [31]:
#(Write code here)
growth_rate = [round(growth_rate[i], 2) for i in range(len(growth_rate))]
growth_rate

[nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 1.0,
 2.11,
 0.53,
 0.73,
 0.19,
 0.83,
 0.83,
 1.27,
 3.22,
 0.96,
 0.97,
 0.99,
 1.01,
 1.91,
 0.39,
 0.96,
 1.0,
 0.94,
 -10.22]

## Step 16 - Add the list of the percentages to the dataframe as a new column ("PCT_CHANGE")

Not as hard as you may think. If you get stuck, you think too hard. Google it and you will find the answer.

In [32]:
#(Write code here)
umbc_df['PCT_CHANGE'] = growth_rate
umbc_df.head(10)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,year,PCT_CHANGE
2151,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1996,NaN
9056,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1997,NaN
15923,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1998,NaN
22598,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1999,NaN
29178,163268,University of Maryland-Baltimore County,MD,2.0,NaN,5490.0,2000,NaN
35821,163268,University of Maryland-Baltimore County,MD,2.0,0.6551,5910.0,2001,NaN
42524,163268,University of Maryland-Baltimore County,MD,2.0,0.6327,6362.0,2002,1.00
49156,163268,University of Maryland-Baltimore County,MD,2.0,0.5757,7388.0,2003,2.11
55786,163268,University of Maryland-Baltimore County,MD,2.0,0.7014,8020.0,2004,0.53
62522,163268,University of Maryland-Baltimore County,MD,2.0,0.7143,8520.0,2005,0.73

## Step 17 - Finaly, we can make the plot tuition growth rate year over year - bar first, then line chart

In [33]:
# (write code here)
fig = px.bar(umbc_df, x='year', y = 'PCT_CHANGE')
fig.show()

In [34]:
fig = px.line(umbc_df, x="year", y="PCT_CHANGE")
fig.show()

## Step 18 - Define Growth Rate Function

Since we want to do the same calculation for JHU. Instead of doing it piecemeal as we did for UMBC. Let's create a function which can be reused for any college. This function takes a list of tuitions and return a list of percentage changes year over year. This function can be used later.

In [35]:
#(Write code here)
def pct_change(lst):
  growth_rate = [(lst[i] - lst[i-1])/lst[i-1] for i in range(len(lst))]
  growth_rate = [growth_rate[i]/growth_rate[i-1] for i in range(0, len(growth_rate))]
  growth_rate = [round(growth_rate[i], 2) for i in range(len(growth_rate))]
  return growth_rate

## Step 19 - Get JHU Data

The dataframe contains many years of data of all U.S. colleges. Let's just look at JHU. Filter/query the dataframe to retrieve only rows that belong to JHU. Save the JHU data to a new data frame using a new variable so that the old big data frame is still available for later use.

In [37]:
#(Write code here)
jhu_df = df_all[df_all["INSTNM"].str.contains("Johns Hopkins University")]
jhu_df

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,year
2139,162928,Johns Hopkins University,MD,2.0,NaN,NaN,1996
9046,162928,Johns Hopkins University,MD,2.0,NaN,NaN,1997
15914,162928,Johns Hopkins University,MD,2.0,NaN,NaN,1998
22589,162928,Johns Hopkins University,MD,2.0,NaN,NaN,1999
29169,162928,Johns Hopkins University,MD,2.0,NaN,24930.0,2000
35812,162928,Johns Hopkins University,MD,2.0,0.3431,26210.0,2001
42515,162928,Johns Hopkins University,MD,2.0,0.3506,27390.0,2002
49148,162928,Johns Hopkins University,MD,2.0,0.3060,28730.0,2003
55779,162928,Johns Hopkins University,MD,2.0,0.3071,30140.0,2004
62515,162928,Johns Hopkins University,MD,2.0,0.3509,31620.0,2005
69394,162928,Johns Hopkins University,MD,2.0,0.2792,33900.0,2006
76325,162928,Johns Hopkins University,MD,2.0,0.2571,35900.0,2007
83284,162928,Johns Hopkins University,MD,2.0,0.2609,37700.0,2008
90317,162928,Johns Hopkins University,MD,2.0,0.2782,39150.0,2009
97499,162928,Johns Hopkins University,MD,2.0,0.2225,40680.0,2010
104953,162928,Johns Hopkins University,MD,2.0,0.1940,42280.0,2011
112665,162928,Johns Hopkins University,MD,2.0,0.1843,43390.0,2012
120496,162928,Johns Hopkins University,MD,2.0,0.1813,45470.0,2013
128346,162928,Johns Hopkins University,MD,2.0,0.1608,47060.0,2014
136057,162928,Johns Hopkins University,MD,2.0,0.1412,48710.0,2015
143678,162928,Johns Hopkins University,MD,2.0,0.1284,50410.0,2016
150886,162928,Johns Hopkins University,MD,2.0,0.1254,52170.0,2017
157935,162928,Johns Hopkins University,MD,2.0,0.1148,53740.0,2018
164718,162928,Johns Hopkins University,MD,2.0,0.1117,55350.0,2019
171396,162928,Johns Hopkins University,MD,2.0,0.1106,54160.0,2020

## Step 20 - Plot JHU's in-state tuition overtime

Let's plot bar and then line chart.

In [38]:
# <14> 
# Plot JHU's in-state tuition overtime from 1996 to 2019. 
# Let's plot bar and line chart together

#(Write code here)

fig = px.bar(jhu_df, x='year', y = 'TUITIONFEE_IN')
fig.show()

In [39]:
fig = px.line(jhu_df, x='year', y = 'TUITIONFEE_IN')
fig.show()

## Step 21 - Calculate Tuition Growth Rate using the Function defined earlier

In [40]:
# Write code here
inst_tuition = jhu_df['TUITIONFEE_IN'].to_list()
inst_tuition

[nan,
 nan,
 nan,
 nan,
 24930.0,
 26210.0,
 27390.0,
 28730.0,
 30140.0,
 31620.0,
 33900.0,
 35900.0,
 37700.0,
 39150.0,
 40680.0,
 42280.0,
 43390.0,
 45470.0,
 47060.0,
 48710.0,
 50410.0,
 52170.0,
 53740.0,
 55350.0,
 54160.0]

In [41]:
growth_rate = pct_change(inst_tuition)
growth_rate

[nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 0.88,
 1.09,
 1.0,
 1.0,
 1.47,
 0.82,
 0.85,
 0.77,
 1.02,
 1.01,
 0.67,
 1.83,
 0.73,
 1.0,
 1.0,
 1.0,
 0.86,
 1.0,
 -0.72]

## Step 22 - Add the list of percentage changes to the dataframe as a new column ("PCT_CHANGE")

In [42]:
#(Write code here)

jhu_df['PCT_CHANGE'] = growth_rate
jhu_df.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,year,PCT_CHANGE
2139,162928,Johns Hopkins University,MD,2.0,NaN,NaN,1996,NaN
9046,162928,Johns Hopkins University,MD,2.0,NaN,NaN,1997,NaN
15914,162928,Johns Hopkins University,MD,2.0,NaN,NaN,1998,NaN
22589,162928,Johns Hopkins University,MD,2.0,NaN,NaN,1999,NaN
29169,162928,Johns Hopkins University,MD,2.0,NaN,24930.0,2000,NaN

## Step 23 - Plot the JHU percentage changes tuitions over time

Bar plot first, then line plot.

In [43]:
#(Write code here)

fig = px.bar(jhu_df, x='year', y = 'PCT_CHANGE')
fig.show()

In [44]:
fig = px.line(jhu_df, x="year", y="PCT_CHANGE")
fig.show()

## Step 24 - Compare UMBC and JHU 

In order to plot both UMBC and JHU tuition change over time in the same plot, we need to combine the two datasets using the common key of YEAR. 

First make a umbc2 dataframe with only two columns needed. We don't need other columns. Also change the column name from "PCT_CHANGE" to "UMBC_PCT" in preparation for the merge. This is because both umbc and jhu dataframe have the same column name "PCT_CHANGE", we rename them to there is no collision during the merge. BTW, Pandas handles collision gracefully, Feel free to try it without changing the column names.

In [46]:
#(Write code here)
umbc_df_new = umbc_df[['year', 'PCT_CHANGE']]

In [47]:
umbc_df_new.rename(columns = {'PCT_CHANGE':'UMBC_PCT'}, inplace = True)
umbc_df_new.head()

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:5047: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

       year  UMBC_PCT
2151   1996       NaN
9056   1997       NaN
15923  1998       NaN
22598  1999       NaN
29178  2000       NaN

## Step 25 

Then make a jhu2 dataframe with only two columns needed. WE don't need other columns. Also change the column name from "PCT_CHANGE" to "JHU_PCT"  in preparation for the merge

In [48]:
#(Write code here)

jhu_df_new = jhu_df[['year', 'PCT_CHANGE']]

In [49]:
jhu_df_new.rename(columns = {'PCT_CHANGE':'JHU_PCT'}, inplace = True)
jhu_df_new.head()

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:5047: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

       year  JHU_PCT
2139   1996      NaN
9046   1997      NaN
15914  1998      NaN
22589  1999      NaN
29169  2000      NaN

## Step 26 - Merger the two data frames and display the new dataframe

In [50]:
#(Write code here)

merged_umbc_jhu = pd.merge(umbc_df_new, jhu_df_new, on ='year')

In [52]:
merged_umbc_jhu.shape

(25, 3)

In [51]:
merged_umbc_jhu.head()

   year  UMBC_PCT  JHU_PCT
0  1996       NaN      NaN
1  1997       NaN      NaN
2  1998       NaN      NaN
3  1999       NaN      NaN
4  2000       NaN      NaN

## Step 27 - Plot UMBC and JHU separately on the same line plot

In [53]:
#(Write code here)

fig = px.line(merged_umbc_jhu, x='year', y=['UMBC_PCT','JHU_PCT'])
fig.show()

## Step 28 - Document your observation of the comparison plots using the following Markdown cell

#### Based on my observation of the plots, we can say the following:

- There are ups and downs in the growth rate of tuition of the two institutes. UMBC tuition change rate varies more than JHU tuition rate.
- The tuition growth rate is more negative for UMBC than for JHU which means that the tuition changed more drastically for UMBC than for JHU in 2020.

In [ ]:
# The end.